routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if (Auth::check()) {
        return redirect()->route('app');
    }
    return view('welcome');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin|moderator'])->group(function () {
    Route::resource('users', 'Admin\UserController');
    Route::get('users/{id}/products', 'Admin\UserController@products')->name('users.products');
    Route::resource('products', 'Admin\ProductController');
    Route::patch('products/{id}/accept', 'Admin\ProductController@accept')->name('products.accept');
    Route::get('', 'Admin\DashboardController@index')->name('dashboard');
    Route::get('stats', 'Admin\StatsController@index')->name('stats');
});

Auth::routes();

Route::any('app/{query?}', 'AppController@index')->where('query', '.*')
    ->middleware(['auth'])->name('app');

app/User.php
<?php

namespace App;

use App\Notifications\ResetPassword;
use Illuminate\Auth\MustVerifyEmail;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Contracts\Auth\MustVerifyEmail as MustVerifyEmailContract;

class User extends Authenticatable
{
    use Notifiable;

//    protected $with = ['role', 'settings'];

    /* use field in Blade with Carbon */
    protected $dates = [
        'last_login_at'
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'api_token', 'gender',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /* Getters and helpers */
    public function isMale(): bool
    {
        return $this->gender === 'm' ? true : false;
    }

    public function hasRole($roles): bool
    {
        foreach ($roles as $role) {
            if ($this->role->name === $role)
                return true;
        }
        return false;
    }

    public function getThemeName($prefix = false): string
    {
        /* prefix needed for Bootstrap classes: active */
        if ($this->settings->theme) {
            return $prefix ? '-pink' : 'pink';
        } else {
            return $prefix ? '-primary' : 'primary';
        }
    }

    public function getThemeNameActive(): string
    {
        return $this->settings->theme ? '-pink' : '';
    }


    /* Relations */
    // Products
    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function userAcceptedProducts()
    {
        return $this->hasMany(Product::class)
            ->whereNotNull('products.accepted_by');
    }

    public function acceptedByUser()
    {
        return $this->hasMany(Product::class, 'accepted_by');
    }

    // Meals
    public function meals()
    {
        return $this->hasMany(Meal::class);
    }

    // Roles
    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    // Settings
    public function settings()
    {
        return $this->hasOne(Settings::class);
    }

    // Measurements
    public function measurements()
    {
        return $this->hasMany(Measurement::class);
    }

    // Goal
    public function goal() {
        return $this->hasOne(Goal::class);
    }

    public function sendPasswordResetNotification($token)
    {
        // Your your own implementation.
        $this->notify(new ResetPassword($token));
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Product;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    const ORDER_BY_FIELDS = ['id', 'name', 'email'];

    public function __construct()
    {
        $this->middleware('role:admin', ['only' => ['update']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($search = $request->query('search')) {
//            $users = User::whereHas('role', function ($q) use ($search) {
//                    $q->where('name', 'like', "%{$search}%");
//                });
            $users = User::where('name', 'like', "%{$search}%")
                ->orWhere('email', 'like', "%{$search}%")
                ->orWhere('id', (int) $search)
                ->orWhereHas('role', function ($q) use ($search) {
                    $q->where('name', 'like', "%{$search}%");
                });
        } else {
            $users = User::query();
        }

        $orderBy = $request->query('orderBy') ?? 'id';
        $order = $request->query('order') ?? 'asc';

        if (in_array($orderBy, self::ORDER_BY_FIELDS)) {
            $users = $users->orderBy($orderBy, $order);
        }

        $users = $users->with('role')->paginate(10);
        return view('admin.user.index', ['users' => $users]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
//        $user = User::findOrFail($id)->with(['roles' => function ($query) {
//            $query->select('name');
//        }])->get();

        $user = User::with('role')->findOrFail($id);
        return view('admin.user.show', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $user->blocked = !$user->blocked;
        if ($user->blocked) {
            $user->blocked_at = date('Y-m-d H:i:s');
        } else {
            $user->blocked_at = null;
        }
        $user->save();
        return back();
    }

    /**
     * Returns page with products added by direct user.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function products($id)
    {
        $user = User::findOrFail($id);
        $products = Product::with('userWhoAccepted')
            ->where('user_id', $id)
            ->whereNotNull('accepted_by')
            ->orderBy('id', 'desc')
            ->paginate(10);

        return view('admin.user.show', ['user' => $user, 'products' => $products]);
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserUpdateSettings;
use App\Http\Resources\ProductCollection;
use App\Product;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Update user settings.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function updateSettings(UserUpdateSettings $request)
    {
        $user = $request->user();
        $settings = $user->settings;
        $settings->theme = $request->theme;
        $settings->show_numbers_in_bars = $request->show_numbers_in_bars;
        $settings->number_of_items_in_table = $request->number_of_items_in_table;

        $settings->save();

        return $settings;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Return products which belong to user
     * @param Request $request
     * @return ProductCollection
     */
    public function products(Request $request)
    {
        $user = $request->user();

        return new ProductCollection($user->products()->whereNull('accepted_by')->get());
    }
}

resources/views/admin/user/includes/show-products.blade.php
<p class="card-text">
    <table class="table table-responsive-sm">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nazwa produktu</th>
            <th scope="col">Dodany dnia</th>
            <th scope="col">Zaakceptowany przez</th>
            <th scope="col" class="text-right">Opcje</th>
        </tr>
        </thead>
        <tbody>
        @foreach($products as $product)
            <tr>
                <th scope="row">{{ $product->id }}</th>
                <td>{{ $product->name }}</td>
                <td>{{ $product->proposed_at }}</td>
                <td>
                    @if($product->accepted_by)
                        <a href="{{ route('admin.users.show', ['id' => $product->userWhoAccepted->id]) }}">
                            {{ $product->userWhoAccepted->name }}
                        </a>
                    @endif
                </td>
                <td class="text-right">
                    <a href="{{ route('admin.products.show', ['id' => $product->id]) }}" class="btn btn-{{ Auth::user()->getThemeName() }} btn-sm">
                        <i class="fas fa-info-circle"></i> Szczegóły
                    </a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</p>

resources/views/admin/user/includes/show-profile.blade.php
<p class="card-text">
    {{--<img src="http://www.taxtoken.in/wp-content/uploads/2017/11/300X300-2.png" class="rounded" width="150px" height="150px">--}}

    <p>
        @if($user->role->name === 'admin')
            <span class="badge badge-danger">{{ $user->role->name }}</span>
        @elseif($user->role->name === 'moderator')
            <span class="badge badge-info">{{ $user->role->name }}</span>
        @else
            <span class="badge badge-primary">{{ $user->role->name }}</span>
        @endif

        <span class="badge badge-{{ $user->blocked ? 'danger' : 'success' }}">
            {{ $user->blocked ? "zablokowany {$user->blocked_at}" : ($user->gender == 'm' ? 'aktywny' : 'aktywna') }}
        </span>
    </p>
    <p><strong>Nazwa użytkownika: </strong>
        {{ $user->name }}
        <i class="fas fa-{{ $user->gender == 'm' ? 'mars' : 'venus' }}"></i>
    </p>
    <p><strong>Email:</strong> {{ $user->email }}</p>
    <p><strong>Zarejestrowany:</strong> {{ $user->created_at }}</p>
    <p><strong>Użytkownik od:</strong> {{ $user->created_at->diffForHumans() }}</p>
    @if($user->updated_at)
        <p><strong>Modyfikowany:</strong> {{ $user->updated_at->format('d/m/Y H:m') }} ({{ $user->updated_at->diffForHumans() }})</p>
    @endif

    @if(Auth::user()->role->name === 'admin')
    <form method="POST" action="{{ route('admin.users.update', ['id' => $user->id]) }}" id="myForm">
        {{ method_field('patch') }}
        {{ csrf_field() }}
        <button type="button" class="btn btn-{{ $user->blocked ? 'success' : 'danger' }}" data-toggle="modal" data-target="#exampleModalCenter">
            {{ $user->blocked ? 'Odblokuj' : 'Zablokuj' }}
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">{{ $user->blocked ? 'Odblokuj użytkownika' : 'Zablokuj użytkownika' }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ $user->blocked ? 'Odblokować' : 'Zablokować' }} użytkownika. Jesteś {{ Auth::user()->gender == 'm' ? 'pewien' : 'pewna' }}?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Anuluj</button>
                    <button type="submit" class="btn btn-primary">Potwierdź</button>
                </div>
            </div>
        </div>
        </div>
    </form>
    @endif
</p>