routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if (Auth::check()) {
        return redirect()->route('app');
    }
    return view('welcome');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin|moderator'])->group(function () {
    Route::resource('users', 'Admin\UserController');
    Route::get('users/{id}/products', 'Admin\UserController@products')->name('users.products');
    Route::resource('products', 'Admin\ProductController');
    Route::patch('products/{id}/accept', 'Admin\ProductController@accept')->name('products.accept');
    Route::get('', 'Admin\DashboardController@index')->name('dashboard');
    Route::get('stats', 'Admin\StatsController@index')->name('stats');
});

Auth::routes();

Route::any('app/{query?}', 'AppController@index')->where('query', '.*')
    ->middleware(['auth'])->name('app');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name', 'proteins', 'carbs', 'fats', 'calories', 'user_id',
    ];

    protected $dates = [
            'proposed_at'
    ];

    /* Relations */
    // User
    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function userWhoAccepted()
    {
        return $this->belongsTo(User::class, 'accepted_by');
    }

    // Product
    public function meals()
    {
        return $this->belongsToMany(Meal::class)->withPivot('weight');
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\ProductEditRequest;
use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->validate($request, [
            'proposed' => 'boolean'
        ]);

        $search = $request->query('search');
        $proposed = $request->query('proposed');

        if ($proposed) {
            $products = Product::whereNotNull('proposed_at')->whereNull('accepted_by');
        } else {
            $products = Product::whereNotNull('accepted_by');
        }

        $products = $products
            ->where('name', 'like', "%{$search}%")
            ->orWhere('id', (int) $search);
        $products = $products->with(['creator', 'userWhoAccepted'])->orderBy('proposed_at', 'DESC')->paginate(10);

//        return $products;
        return view('admin.products.index', ['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
//    public function create()
//    {
//        //
//    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
//    public function store(Request $request)
//    {
//        //
//    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::findOrFail($id);
        return view('admin.products.show', ['product' => $product]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        return view('admin.products.edit', ['product' => $product]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductEditRequest $request, $id)
    {
        $product = Product::findOrFail($id);
        $product->name = $request['name'];
        $product->proteins = $request['proteins'];
        $product->carbs = $request['carbs'];
        $product->fats = $request['fats'];
        if ($request['isGlobal']) {
            $product->accepted_by = Auth::id();
        } else {
            $product->accepted_by = null;
        }
        $product->save();

        $request->session()->flash('status', "Produkt {$product->name} zaktualizowano!");
        return view('admin.products.show', ['product' => $product]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function accept(Request $request, $id)
    {
        $product = Product::findOrFail($id);
        if ($product->accepted_by) {
            $product->accepted_by = null;
        } else {
            $product->accepted_by = Auth::id();
        }
        $product->save();
        $request->session()->flash('status', "Produkt {$product->name} dodany do globalnej puli!");

        return back();
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = $request->user();
        $search = $request->get('search');
        if ($search) {
            $products = Product::where([
                ['name', 'like', "%{$search}%"],
                ['user_id', $user->id]
            ])->orWhere([
                ['name', 'like', "%{$search}%"],
                ['user_id', '!=', $user->id],
                ['accepted_by', '!=', 'null']
            ])->take(5)->get();
        } else {
            $products = Product::all();
        }
        return $products;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|min:3',
            'proteins' => 'required|numeric|min:0',
            'carbs' => 'required|numeric|min:0',
            'fats' => 'required|numeric|min:0',
            'calories' => 'required|numeric|min:0',
        ]);

        $product = Product::create([
            'name' => $request['name'],
            'proteins' => $request['proteins'],
            'carbs' => $request['carbs'],
            'fats' => $request['fats'],
            'calories' => $request['calories'],
            'user_id' => $request->user()->id
        ]);

        return $product;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id, Request $request)
    {
        $user = $request->user();
        $isOwnerOfProduct = $user->products()->where('id', '=', $id)->exists();
        if (!$isOwnerOfProduct) {
            return response()->json(['message' => 'Not authorized'], 401);
        }
        $product = Product::findOrFail($id);

        return $product;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string|min:3',
            'proteins' => 'required|numeric',
            'carbs' => 'required|numeric',
            'fats' => 'required|numeric',
            'calories' => 'required|numeric',
        ]);
        $product = Product::findOrFail($id);

        $product->name = $request->name;
        $product->proteins = $request->proteins;
        $product->carbs = $request->carbs;
        $product->fats = $request->fats;
        $product->calories = $request->calories;

        $product->save();

        return $product;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
        $user = $request->user();
        $product = Product::findOrFail($id);
        $creator = $product->creator;

        if ($user->id !== $creator->id) {
            return response()->json(['message' => 'Not authorized'], 401);
        }

        $product->delete();
        return response()->json(["message" => "Product of id: {$product->id} deleted"], 200);
    }

    public function proposeProduct($id, Request $request)
    {
        $user = $request->user();
        $product = $user->products()->findOrFail($id);

        $product->proposed_at = new \DateTime();
        $product->save();
        return response()->json(["message" => "Product has been proposed"], 200);
    }
}

resources/views/admin/products/edit.blade.php
@extends('layouts.app')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @if(Session::has('status'))
        <p class="alert alert-success">{{ Session::get('status') }}</p>
    @endif

    <div class="card">
        <div class="card-body">
            <h1>{{ $product->name }}</h1>

            <form method="POST" action="{{ route('admin.products.update', ['id' => $product->id]) }}">
                {{ method_field('PATCH') }}
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="productName">Nazwa produktu</label>
                    <input type="text" class="form-control" id="productName" name="name" value="{{ $product->name }}">
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="productProteins">Białko</label>
                        <input type="text" class="form-control" id="productProteins" name="proteins" value="{{ $product->proteins }}">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="productCarbs">Węglowodany</label>
                        <input type="text" class="form-control" id="productCarbs" name="carbs" value="{{ $product->carbs }}">
                    </div>
                </div>
                <div class="form-row">
                    {{--<div class="form-group col-md-6">--}}
                        {{--<label for="productSugars">Cukry</label>--}}
                        {{--<input type="text" class="form-control" id="productSugars" name="sugars" value="{{ $product->sugars }}">--}}
                    {{--</div>--}}
                    <div class="form-group col-md-6">
                        <label for="productFats">Tłuszcz</label>
                        <input type="text" class="form-control" id="productFats" name="fats" value="{{ $product->fats }}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="productCalories">Kalorie</label>
                    <input type="text" class="form-control" id="productCalories" name="calories" value="{{ $product->calories }}">
                </div>

                <div class="form-check">
                    <input class="form-check-input" value="test" type="checkbox" name="isGlobal" id="productGlobal" {{ $product->accepted_by ? 'checked' : '' }}>
                    <label class="form-check-label" for="productGlobal">
                        Produkt globalny
                    </label>
                </div>

                <div class="float-right">
                    <a href="{{ route('admin.products.show', ['id' => $product->id]) }}" class="btn btn-link">Anuluj</a>
                    <button type="submit" class="btn btn-{{ Auth::user()->getThemeName() }}">Zapisz</button>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.app')

@section('content')

    {{--<div class="alert alert-info" role="alert">--}}
        {{--<p>Wyszukiwanie dozwolone po: <strong>ID</strong>, <strong>nazwa</strong><br>--}}
            {{--Aby zresetować filtry należy wysłac pusty ciąg znaków.--}}
        {{--</p>--}}
        {{--<p>--}}
            {{--<strong>Produkty globalne</strong> są dostępne dla każdego użytkownika<br />--}}
            {{--<strong>Produkty zaproponowane</strong> to produkty prywatne, którymi użytkownik chce się podzielić z innymi.--}}
            {{--Muszą być one zaakceptowane przez <strong>admina</strong> lub <strong>moderatora</strong>--}}
        {{--</p>--}}
    {{--</div>--}}

    <form method="GET" action="{{ route('admin.products.index') }}" class="mb-2">
        <div class="form-row">
            <div class="col-8 col-md-9 col-lg-10">
                <input type="text" class="form-control" name="search" placeholder="Szukaj..." value="{{ Request::get('search') }}">
            </div>
            <div class="col-4 col-md-3 col-lg-2">
                <button class="btn btn-{{ Auth::user()->getThemeName() }} btn-block" type="submit"><i class="fas fa-search"></i> Szukaj</button>
            </div>
        </div>
        @if(Request::get('proposed'))
            <input type="hidden" name="proposed" value="1">
        @endif
    </form>

    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link {{ Route::is('admin.products.index') && !Request::get('proposed') ? 'active' : '' }}"
                       href="{{ route('admin.products.index') }}">
                        Produkty globalne
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ Route::is('admin.products.index') && Request::get('proposed') ? 'active' : '' }}"
                       href="{{ route('admin.products.index', ['proposed' => true]) }}">
                        Produkty zaproponowane
                    </a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <table class="table table-responsive-md">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nazwa produktu</th>
                    <th scope="col">Dodany przez</th>
                    <th scope="col">Dodany dnia</th>
                    @if(!Request::get('proposed'))
                        <th scope="col">Zaakceptowany przez</th>
                    @endif
                    <th scope="col" class="text-right">Opcje</th>
                </tr>
                </thead>
                <tbody>
                @foreach($products as $product)
                    <tr>
                        <th scope="row">{{ $product->id }}</th>
                        <td>{{ $product->name }}</td>
                        <td>
                            <a href="{{ route('admin.users.show', ['id' => $product->creator->id]) }}">
                                {{ $product->creator->name }}
                            </a>
                        </td>
                        <td>{{ $product->proposed_at }}</td>
                        @if($product->accepted_by)
                            <td>
                                <a href="{{ route('admin.users.show', ['id' => $product->userWhoAccepted->id]) }}">
                                    {{ $product->userWhoAccepted->name }}
                                </a>
                            </td>
                        @endif
                        <td class="text-right">
                            {{--<a href="{{ route('admin.products.edit', ['id' => $product->id]) }}" class="btn btn-dark btn-sm">--}}
                                {{--<i class="fas fa-edit"></i> Edit--}}
                            {{--</a>--}}
                            <a href="{{ route('admin.products.show', ['id' => $product->id]) }}" class="btn btn-{{ Auth::user()->getThemeName() }} btn-sm">
                                <i class="fas fa-info-circle"></i> Szczegóły
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

    {{--Pagination--}}
    <div class="float-right mt-2">
        {{ $products->onEachSide(1)->links() }}
    </div>

@endsection

resources/views/admin/products/show.blade.php
@extends('layouts.app')

@section('content')
    @if(Session::has('status'))
        <p class="alert alert-success">{{ Session::get('status') }}</p>
    @endif

    @if($product->proposed_at && !$product->accepted_by)
        <form method="POST" action="{{ route('admin.products.accept', ['id' => $product->id]) }}">
            {{ method_field('PATCH') }}
            {{ csrf_field() }}
            <button type="submit" class="btn btn-success mb-2 btn-block btn-sm">Dodaj jako produkt globalny</button>
        </form>
    @endif

    <div class="card">
        <div class="card-body">
            <h1>
                {{ $product->name }}
                <a href="{{ route('admin.products.edit', ['id' => $product->id]) }}" class="btn btn-{{ Auth::user()->getThemeName() }} float-right">
                    <i class="fas fa-edit"></i> Edytuj
                </a>
            </h1>
            <h4 class="mt-4">Tabela makroskładników</h4>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Białko</th>
                    <th scope="col">Węglowodany</th>
                    {{--<th scope="col" class="text-normal">Cukry</th>--}}
                    <th scope="col">Tłuszcz</th>
                    <th scope="col">Kalorie</th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ $product->proteins }}</td>
                        <td>{{ $product->carbs }}</td>
{{--                        <td>{{ $product->sugars }}</td>--}}
                        <td>{{ $product->fats }}</td>
                        <td>{{ $product->calories }}</td>
                    </tr>
                </tbody>
            </table>

            <p class="mt-4">
                <strong>Utworzony przez: </strong>
                <a href="{{ route('admin.users.show', ['id' => $product->creator->id]) }}">
                    {{ $product->creator->name }}
                </a>
                , {{ $product->created_at->diffForHumans() }}
            </p>

        </div>
    </div>
@endsection