routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if (Auth::check()) {
        return redirect()->route('app');
    }
    return view('welcome');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin|moderator'])->group(function () {
    Route::resource('users', 'Admin\UserController');
    Route::get('users/{id}/products', 'Admin\UserController@products')->name('users.products');
    Route::resource('products', 'Admin\ProductController');
    Route::patch('products/{id}/accept', 'Admin\ProductController@accept')->name('products.accept');
    Route::get('', 'Admin\DashboardController@index')->name('dashboard');
    Route::get('stats', 'Admin\StatsController@index')->name('stats');
});

Auth::routes();

Route::any('app/{query?}', 'AppController@index')->where('query', '.*')
    ->middleware(['auth'])->name('app');

resources/views/layouts/includes/sidebar.blade.php
<div class="col-md-3 mb-3">
    <div class="list-group nav-list">
        <span class="text-muted">Ogólne</span>
        <a href="{{ route('admin.dashboard') }}"
           class="list-group-item list-group-item-action {{ Route::is('admin.dashboard*') ? 'active' . Auth::user()->getThemeNameActive() : '' }}">
            <i class="fas fa-tachometer-alt"></i> Panel główny
        </a>
        <a href="{{ route('admin.stats') }}"
           class="list-group-item list-group-item-action {{ Route::is('admin.stats*') ? 'active' . Auth::user()->getThemeNameActive() : '' }}">
            <i class="fas fa-chart-line"></i> Statystyki
        </a>

        <div class="dropdown-divider"></div>
        <span class="text-muted">Baza danych</span>
        <a href="{{ route('admin.users.index') }}"
           class="list-group-item list-group-item-action {{ Route::is('admin.users*') ? 'active' . Auth::user()->getThemeNameActive() : '' }}">
            <i class="fas fa-users"></i> Użytkownicy
        </a>
        <a href="{{ route('admin.products.index') }}"
           class="list-group-item list-group-item-action {{ Route::is('admin.products*') ? 'active' . Auth::user()->getThemeNameActive() : '' }}">
            <i class="fas fa-utensils"></i> Produkty
        </a>

        {{--TODO - product tags--}}
        {{--<a href="#"--}}
           {{--class="list-group-item list-group-item-action {{ Route::is('admin.tags*') ? 'active' : '' }}">--}}
            {{--<i class="fas fa-tags"></i> Product tags--}}
        {{--</a>--}}
    </div>
</div>